### ISSUE TITLE
MotionCor3 1.0.1, with option "-Serial 1" process holds excessive memory.

### ISSUE THREAD

**Issue by larsonmattr** [czimaginginstitute/MotionCor3#13]
When running with -Serial option turned on, this version of MotionCor3 appears to be using excessive memory when iterating over a datasets of 1000 micrographs:

~ 500 micrographs processed:
 
```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                  
 113220 1111471+  20   0  363.5g 328.2g 874640 S 294.1  65.2  59:56.75 MotionCor3  
```
 
 ~ 750 micrographs processed:
```
     PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                     
 113220 1111471+  20   0  491.0g 453.5g 953284 S 278.2  90.1  83:10.06 MotionCor3  
```

After about 750 micrographs the process had allocated over 450GB of memory, and this is possibly a memory leak that could kill the process eventually.

**Comment by apeck12** [comment]
What resources are you requesting? We often use:
```
--cpus-per-task=16
--mem-per-cpu=196G
```
when running in `-Serial` mode for larger datasets. Did you find that you needed fewer compute resources when running MotionCor2 for similarly sized datasets?
