### ISSUE TITLE
MotionCor3 1.0.1, "-InTiff <folder>" with "-Serial 1" results in issues with long folder path names.

### ISSUE THREAD

**Issue by larsonmattr** [czimaginginstitute/MotionCor3#14]
Issue: It appears the -InTiff has a problem with the longer path names and appends extra/incorrect strings at the end.

1. This is reproducible as below:

"MotionCor3 -InTiff /mnt/hpc_users/share/resources/test/datasets/2022_02_18/images/ -InSuffix fractions.tiff -OutMrc corrected/ -Patch 7 5 -Gpu 0 1 2 3 -Gain /mnt/hpc_users/share/resources/test/datasets/2022_02_18/gain.mrc -FlipGain 2 -RotGain 2 -Serial 1"

which fails with an error as below: 

"Error: cannot open folder
   /mnt/hpc_users/share/resources/test/datasets/2022_02_18/images/Game.ex?in CStackFolder::mReadFolder.

Error: no input image files are found."

2. Similar command as:

submit_to_a5000.sh MotionCor3 -InTiff images/ -InSuffix fractions.tiff -OutMrc corrected/ -Patch 7 5 -Gpu 0 1 2 3 -Gain gain.mrc -FlipGain 2 -RotGain 2 -Serial 1

Will run correctly.

**Comment by apeck12** [comment]
The `-InTiff` argument should accept file paths up to 256 characters in length. If the input file path is shorter than that, is it possible that permissions change when using the submission script to run MotionCor on a node?
