### ISSUE TITLE
TIFFReadDirectory warnings when reading in EER movies

### ISSUE THREAD

**Issue by theju-at-nimgs** [czimaginginstitute/MotionCor3#16]
I'm getting several hundred pages of "TIFFReadDirectory: Warning, Unknown field with tag 65002 (0xfdea) encountered" warning message whenever we try to read a movie collected on a F3 camera. When reading a TIF movie from a K3 camera we don't have any warnings.

Although it prints these warnings the reset of the steps are completed correctly.

Using MotionCor3 1.0.1 on Cuda 11.8

**Comment by szhengczii** [comment]
This warning message originates in libtiff. You can add 2>/dev/null at the end of command line to suppress it. I haven't found way to get rid of it in MotionCor2/3. Any better suggestions are much appreciated.
