### ISSUE TITLE
Compiliation error with static binary library files (PIE object issues)

### ISSUE THREAD

**Issue by charbj** [czimaginginstitute/MotionCor3#4]
Hi, 

Having some issues with compilation. I've tried passing -fPIE and -no-pie to g++, but the error persists. 

g++ and gcc versions are 9.4.0, trying to compile on Ubuntu 20.04.4 LTS. CUDA 11.6, nvcc V11.6.55.

> `/usr/bin/ld: /usr/local/programs/motioncor3/Lib/libmrcfile.a(CLoadExtHeader.o): relocation R_X86_64_32 against symbol __gxx_personality_v0@@CXXABI_1.3' can not be used when making a PIE object; recompile with -fPIE
> /usr/bin/ld: /usr/local/programs/motioncor3/Lib/libmrcfile.a(CLoadImage.o): relocation R_X86_64_32 against symbol __gxx_personality_v0@@CXXABI_1.3' can not be used when making a PIE object; recompile with -fPIE
> /usr/bin/ld: /usr/local/programs/motioncor3/Lib/libmrcfile.a(CLoadMrc.o): relocation R_X86_64_32 against symbol __gxx_personality_v0@@CXXABI_1.3' can not be used when making a PIE object; recompile with -fPIE
> /usr/bin/ld: /usr/local/programs/motioncor3/Lib/libmrcfile.a(CSaveMrc.o): relocation R_X86_64_32 against symbol __gxx_personality_v0@@CXXABI_1.3' can not be used when making a PIE object; recompile with -fPIE
> /usr/bin/ld: /usr/local/programs/motioncor3/Lib/libmrcfile.a(CSaveMainHeader.o): relocation R_X86_64_32 against symbol __gxx_personality_v0@@CXXABI_1.3' can not be used when making a PIE object; recompile with -fPIE
> /usr/bin/ld: /usr/local/programs/motioncor3/Lib/libutil.a(Util_LinEqs.o): relocation R_X86_64_32 against '.rodata' can not be used when making a PIE object; recompile with -fPIE
> /usr/bin/ld: /usr/local/programs/motioncor3/Lib/libutil.a(Util_Thread.o): relocation R_X86_64_32 against symbol '_ZTV11Util_Thread' can not be used when making a PIE object; recompile with -fPIE
> /usr/bin/ld: /usr/local/programs/motioncor3/Lib/libutil.a(Util_FileName.o): relocation R_X86_64_32 against '.rodata' can not be used when making a PIE object; recompile with -fPIE
> /usr/bin/ld: /usr/local/programs/motioncor3/Lib/libutil.a(Util_String.o): relocation R_X86_64_32 against '.rodata' can not be used when making a PIE object; recompile with -fPIE
> collect2: error: ld returned 1 exit status
> make: *** [makefile11:160: exe] Error 1`

Thanks. 
CBJ

**Comment by homurachan** [comment]
Same problem here. It seems those three ".a" files in "MotionCor3/Lib" need to be recompiled by the author.

**Comment by dirrei** [comment]
Same issue here, on Ubuntu 20.04 with Cuda 11.8 .

**Comment by k-haru** [comment]
The following changes worked for me but have not been tested.
makefile11
```
exe: $(OBJS)
        @$(NVCC) -g -G -m64 $(OBJS) \
        $(PRJLIB)/libmrcfile.a $(PRJLIB)/libutil.a $(PRJLIB)/libcuutil.a \
        -L$(CUDALIB) \
        -L$(CONDA)/lib \
        -L/usr/lib64 \
        -Xcompiler -no-pie \ 
        -lcufft -lcudart -lcuda -lnvToolsExt -ltiff -lc -lm -lpthread \
        -o MotionCor3
        @echo MotionCor3 has been generated.
```

**Comment by homurachan** [comment]
> The following changes worked for me but have not been tested. makefile11
> 
> ```
> exe: $(OBJS)
>         @$(NVCC) -g -G -m64 $(OBJS) \
>         $(PRJLIB)/libmrcfile.a $(PRJLIB)/libutil.a $(PRJLIB)/libcuutil.a \
>         -L$(CUDALIB) \
>         -L$(CONDA)/lib \
>         -L/usr/lib64 \
>         -Xcompiler -no-pie \ 
>         -lcufft -lcudart -lcuda -lnvToolsExt -ltiff -lc -lm -lpthread \
>         -o MotionCor3
>         @echo MotionCor3 has been generated.
> ```

This really works. After compilation I tested the performances and results, all looking good.

**Comment by yanliu-ss** [comment]
I have the same problem but adding ' -Xcompiler -no-pie 'didn't work. I'm on Ubuntu 20.04.4, CUDA 12.1. Any suggestions?

**Comment by elarquet** [comment]
I have the same problem. Adding ' -Xcompiler -no-pie ' or ' - Xlinker -no-pie ' didn't work (the compilation is carried out without error but the execution of the program gives rise to a segmentation fault). I'm on Ubuntu 22.04, CUDA 12.3.
 It seems those three ".a" files in "MotionCor3/Lib" need to be recompiled by the author with -fPIE flag.

**Comment by MTclement1** [comment]
> I have the same problem. Adding ' -Xcompiler -no-pie ' or ' - Xlinker -no-pie ' didn't work (the compilation is carried out without error but the execution of the program gives rise to a segmentation fault). I'm on Ubuntu 22.04, CUDA 12.3. It seems those three ".a" files in "MotionCor3/Lib" need to be recompiled by the author with -fPIE flag.

I had the segfault only when using -Serial 1 for batch. Does it work for you on single file ?

**Comment by szhengczii** [comment]
We will try to release the source of these .a files as soon as we can.

**Comment by elarquet** [comment]
> > I have the same problem. Adding ' -Xcompiler -no-pie ' or ' - Xlinker -no-pie ' didn't work (the compilation is carried out without error but the execution of the program gives rise to a segmentation fault). I'm on Ubuntu 22.04, CUDA 12.3. It seems those three ".a" files in "MotionCor3/Lib" need to be recompiled by the author with -fPIE flag.
> 
> I had the segfault only when using -Serial 1 for batch. Does it work for you on single file 

Exactly the same issue, work well for a single file, but segmentation fault for -serial 1 option

**Comment by nayimgr** [comment]
> I have the same problem. Adding ' -Xcompiler -no-pie ' or ' - Xlinker -no-pie ' didn't work (the compilation is carried out without error but the execution of the program gives rise to a segmentation fault). I'm on Ubuntu 22.04, CUDA 12.3. It seems those three ".a" files in "MotionCor3/Lib" need to be recompiled by the author with -fPIE flag.

Same problem as above, same version of Ubuntu and CUDA 12.0. The suggested fix didn't work for us.

**Comment by elarquet** [comment]
> We will try to release the source of these .a files as soon as we can.

Hi,
Some news concerning the source of /Lib *.a files ?
Thanks,

**Comment by TimKirk** [comment]
For what it's worth the 

-Xcompiler -no-pie \

fix worked for me just now on Ubuntu 20.04, Cuda 12.3

**Comment by elarquet** [comment]
> For what it's worth the
> 
> -Xcompiler -no-pie \
> 
> fix worked for me just now on Ubuntu 20.04, Cuda 12.3

Could you confirm that  it worked both on single file and using -Serial 1 for batch !

**Comment by TimKirk** [comment]
> > For what it's worth the
> > -Xcompiler -no-pie \
> > fix worked for me just now on Ubuntu 20.04, Cuda 12.3
> 
> Could you confirm that it worked both on single file and using -Serial 1 for batch !

Sorry for the slow response - I just run the computers here so had to get someone with data to test the apparently successful build actually worked properly.

I was told it seemed to be working fine : "Serial mode is slower than RELION's implementation (using 4 MPI and 12 threads).  RELION used to run multiple MotionCor2 processes in parallel and each isn't using all GPU memory so I tried that and that is faster than RelionCor."

I hope that's what you were wanting to know. If there are more tests I can run without need my own datasets, let me know.

**Comment by elarquet** [comment]
> > > For what it's worth the
> > > -Xcompiler -no-pie 
> > > fix worked for me just now on Ubuntu 20.04, Cuda 12.3
> > 
> > 
> > Could you confirm that it worked both on single file and using -Serial 1 for batch !
> 
> Sorry for the slow response - I just run the computers here so had to get someone with data to test the apparently successful build actually worked properly.
> 
> I was told it seemed to be working fine : "Serial mode is slower than RELION's implementation (using 4 MPI and 12 threads). RELION used to run multiple MotionCor2 processes in parallel and each isn't using all GPU memory so I tried that and that is faster than RelionCor."
> 
> I hope that's what you were wanting to know. If there are more tests I can run without need my own datasets, let me know.


Thanks Tim for this information.

**Comment by elarquet** [comment]
> We will try to release the source of these .a files as soon as we can.

I found a possible explanation regarding the -fPIE compile flag issue: https://www.mjr19.org.uk/IT/pic_pie.html

**Comment by szhengczii** [comment]
Dear colleagues,

We are going to release MotionCor3 1.1.0 this week that has the source code
of .a files. Thanks for helping resolve this issue.

Best
Shawn

**Comment by lucajovine** [comment]
Ah OK, it DOES work if one goes into LibSrc/Mrcfile and LibSrc/Util and recompiles the libraries. I wrongly assumed this was done automatically. Anyway - problem solved and thank you for posting the new version!

**Comment by elarquet** [comment]
> Dear colleagues, We are going to release MotionCor3 1.1.0 this week that has the source code of .a files. Thanks for helping resolve this issue. Best Shawn

Many Thanks Shawn! It works perfectly now after reconstructing Libraries with the -fPIE Flag.
May I make one final request of you?
Can you make available the sources of the libcuutilfft.a and libcuutil.a libraries as you did for libmrcfile.a and libutil.a in the case of the GctfFind software.
Thanks again, kind regards, Eric.

**Comment by szhengczii** [comment]
The next release of GCtfFind, similar to MotionCor3 and AreTomo2, will
merge the needed code in libcuutilfft.a and libcuutil.a and provide the
source code of libutil and libmrcfile. You will have everything you need to
compile it. However, it will take a while for me to have time working on
it. Thanks for your patience and my apologies for the long delay.

Best,
Shawn

**Comment by szhengczii** [comment]
MotionCor3 has provided the source code of these libraries. Recompile the libraries in LibSrc should fix this problem.
