### ISSUE TITLE
undefined reference to `operator delete(void*, unsigned long) in library

### ISSUE THREAD

**Issue by nym4432018** [czimaginginstitute/MotionCor3#9]
MotionCor3/Lib/libmrcfile.a(CLoadMrc.o): In function `Mrc::CLoadMrc::CLoadMrc()':
/home/shawn.zheng/Projs/Mrcfile/../../Projs/Mrcfile/App/CLoadMrc.cpp:14: undefined reference to `operator delete(void*, unsigned long)'
/home/shawn.zheng/Projs/Mrcfile/../../Projs/Mrcfile/App/CLoadMrc.cpp:15: undefined reference to `operator delete(void*, unsigned long)'
/home/shawn.zheng/Projs/Mrcfile/../../Projs/Mrcfile/App/CLoadMrc.cpp:16: undefined reference to `operator delete(void*, unsigned long)'

otionCor3/Lib/libmrcfile.a(CLoadMrc.o): In function `Mrc::CLoadMrc::~CLoadMrc()':
/home/shawn.zheng/Projs/Mrcfile/../../Projs/Mrcfile/App/CLoadMrc.cpp:24: undefined reference to `operator delete(void*, unsigned long)'
/home/shawn.zheng/Projs/Mrcfile/../../Projs/Mrcfile/App/CLoadMrc.cpp:25: undefined reference to `operator delete(void*, unsigned long)'
/home/funabiki_lab/32TBSATA/CryoEM/MotionCor3/Lib/libmrcfile.a(CLoadMrc.o):/home/shawn.zheng/Projs/Mrcfile/../../Projs/Mrcfile/App/CLoadMrc.cpp:26: more undefined references to `operator delete(void*, unsigned long)' follow

MotionCor3/Lib/libutil.a(Util_LinEqs.o): In function `Util_LinEqs::DoIt(float*, float*, int)':
/home/shawn.zheng/Projs/Util/Util_LinEqs.cpp:26: undefined reference to `__cxa_throw_bad_array_new_length'
/home/shawn.zheng/Projs/Util/Util_LinEqs.cpp:27: undefined reference to `__cxa_throw_bad_array_new_length'
/home/shawn.zheng/Projs/Util/Util_LinEqs.cpp:28: undefined reference to `__cxa_throw_bad_array_new_length'

MotionCor3/Lib/libutil.a(Util_LinEqs.o): In function `Util_LinEqs::mSwapRows(float*, float*, int)':
/home/shawn.zheng/Projs/Util/Util_LinEqs.cpp:97: undefined reference to `__cxa_throw_bad_array_new_length'
/home/funabiki_lab/32TBSATA/CryoEM/MotionCor3/Lib/libutil.a(Util_Thread.o): In function `Util_Thread::~Util_Thread()':
/home/shawn.zheng/Projs/Util/Util_Thread.cpp:18: undefined reference to `operator delete(void*, unsigned long)'
collect2: error: ld returned 1 exit status
make: *** [exe] Error 1

Any suggestions?

**Comment by szhengczii** [comment]
@nym4432018: this seems like g++ issue. Can you please run "g++ --version" and let me what it prints out?

**Comment by nym4432018** [comment]
> @nym4432018: this seems like g++ issue. Can you please run "g++ --version" and let me what it prints out?

Thanks a lot for the help. 
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)

**Comment by nym4432018** [comment]
> @nym4432018: this seems like g++ issue. Can you please run "g++ --version" and let me what it prints out?

It compiled successfully after this solution:

yum install gcc-c++
yum install cmake
yum install centos-release-scl
yum install devtoolset-8-gcc devtoolset-8-gcc-c++
scl enable devtoolset-8 -- bash

Thanks a lot for bringing out the g++ compiler version.
